### ISSUE TITLE
Be prepared for upgrade of Consul

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#11]
FYI in newer releases of Consul `github.com/hashicorp/consul/lib/freeport` has been moved to `github.com/hashicorp/consul/sdk/freeport`.

Patch is trivial:

```
--- a/driver_test.go
+++ b/driver_test.go
@@ -27,9 +27,9 @@
        "testing"
        "time"
        "os"

-       "github.com/hashicorp/consul/lib/freeport"
+       "github.com/hashicorp/consul/sdk/freeport"
        "github.com/hashicorp/nomad/client/taskenv"
        ctestutil "github.com/hashicorp/nomad/client/testutil"
        "github.com/hashicorp/nomad/helper/testlog"
        "github.com/hashicorp/nomad/helper/uuid"
```

See also https://github.com/hashicorp/nomad/issues/6785

**Comment by towe75** [comment]
Thank you for pointing it out. Managing the dependencies is still very messy because of the missing go.mod and pinned ugorji/go generator in nomad. I do not dare to touch my go.mod ATM. First i'll focus on improving/modularizing the code base, maybe in the meantime nomad team moves on with their vendoring stuff.

**Comment by onlyjob** [comment]
I completely understand. Nomad's _ugorji/go_ mess causes a lot of frustration not to mention all the days of effort that it cost us... See also https://github.com/hashicorp/nomad/issues/4426, https://github.com/hashicorp/nomad/issues/6537.

**Comment by towe75** [comment]
I did a first step in c3db30c0723eb0b51b912728badaf47b0d2c6561. The plugin depends now on nomad 0.10.1, following go.mod from https://github.com/hashicorp/nomad-skeleton-driver-plugin
Consul is still pinned to 1.4.5 ATM.

**Comment by towe75** [comment]
@onlyjob you might want to have a look at https://github.com/pascomnet/nomad-driver-podman/commit/055a57f551424c3894f7f73e62b71f5ba970cdaa . 

It has a nicer go.mod with dependencies on nomad 0.11.2 and consul 1.7.3. Also the ugorji stuff is replaced by hashicorp/go-msgpack v1.1.5. It would be nice if you could give it a spin before i merge it into master.

Some manual testing and also the unittests in GH actions revealed no problems.
