### ISSUE TITLE
Support for `--tmpfs` option?

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#13]
Probably it would be a good idea to implement. :)

**Comment by towe75** [comment]
Sure, good idea.

**Comment by towe75** [comment]
What's your opinion on simple "--tmpfs" string array vs. complex [mount options](https://www.nomadproject.io/docs/drivers/docker.html#mounts)? I tend to avoid the mount-struct approach until somebody really needs it.

**Comment by onlyjob** [comment]
That's what I had in mind -- just a simple list of locations for `--tmpfs`.  :)

I reckon time will show if anything more sophisticated will ever be needed.

**Comment by towe75** [comment]
Ok, i added a simple "--tmpfs" option, it's directly passed from nomad job to podman without modifications. Again there is a unit test and a small example in the readme. Please check and close.

**Comment by towe75** [comment]
@onlyjob  is it ok to close this issue?

**Comment by onlyjob** [comment]
Yes, thank you very much for implementing. It works well.
