### ISSUE TITLE
handling oom-killer?

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#14]
When allocation is oom-killed the error is very ambiguous. After the incident Nomad repeatedly complaints "Unknown allocation" to logs...

Would it be possible to detect whether allocation failed due to oom-killer?

See also https://github.com/hashicorp/nomad/issues/2203

**Comment by towe75** [comment]
I fixed this right before you opened this issue...
You might want to check the commit from some hours ago: 583c7d1e556e5e61ac4f7e784d9bc2561df48692 . It introduced, amongst other things, a post-mortem container inspect operation and carries podmans oom boolean into the nomad task result.

Would be nice if you can prove that it actually works :-)

**Comment by onlyjob** [comment]
This is much much better now. I've simulated OOM and got a nice and clear `Terminated | Exit Code: 137` message without "Unknown allocation" side effects. Thanks!

Please feel free to close this issue unless error message can be improved to mention "OOM" as a reason for termination.

**Comment by towe75** [comment]
It's completely solved now. I added cleaner logging in the driver. Also a distinctive message is sent back to nomad. A unit test completes the feature.
