### ISSUE TITLE
how to control swap?

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#15]
One of my containers uses swap heavily...  
Is there a way to pass `--memory-swap` and/or `--memory-swapiness` to Podman in order to restrict swap usage?

**Comment by towe75** [comment]
There seems to be an ongoing discussion related to [swap in nomad docker containers](https://github.com/hashicorp/nomad/issues/6085). It will be best to let the user decide about it, so i'll simply expose two more driver specific configuration options.

**Comment by towe75** [comment]
@onlyjob i added more options: memory_reservation, memory_swap and memory_swappiness. Again there is a readme snipped and a unit test. I did not set a default swappiness.

**Comment by onlyjob** [comment]
You are the champion, Thomas. Thank you. I'll test shortly. Perhaps all the new features since 0.0.1 qualify for new release...

**Comment by onlyjob** [comment]
`memory_swappiness` works perfectly and does exactly what I need. Thank you very much, @towe75.
