### ISSUE TITLE
Task failed: 'cannot unmarshal array into Go struct field InspectContainerHostConfig.Tmpfs of type map[string]string'

### ISSUE THREAD

**Issue by brickstool** [pascomnet/nomad-driver-podman#18]
Hello, thanks for creating this driver. 

I am having an issue running the example redis task in the description on CentOS 8 hosts. When I try to run the task, I encounter this error:

    Jan 27 20:33:50 4128528c26eb nomad[6738]:     2020-01-27T20:33:50.200+1100 [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=8a8d7eb3-0d56-e2a3-2e7e-3efc01648873 task=redis error="rpc error: code = Unknown desc = failed to start task, could not inspect container : json: cannot unmarshal array into Go struct field InspectContainerHostConfig.Tmpfs of type map[string]string"

I have tried with and without SELinux enabled. System and version information (both CentOS 8 hosts have the same config):

    [root@4128528c26eb ~]# cat /etc/centos-release
    CentOS Linux release 8.1.1911 (Core)
    
    [root@4128528c26eb ~]# nomad version
    Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)
    
    [root@4128528c26eb ~]# podman version
    Version:            1.4.2-stable2
    RemoteAPI Version:  1 
    Go Version:         go1.12.8
    OS/Arch:            linux/amd64
    
    [root@4128528c26eb ~]# cat /etc/nomad.d/podman.nomad.hcl
    plugin "nomad-driver-podman" {
      config {
        volumes {
          enabled      = true
          selinuxlabel = "z"
        }
      }
    }

    [root@4128528c26eb ~]# dnf list installed | grep varlink
    libvarlink.x86_64                     18-3.el8                                          @anaconda 
    libvarlink-util.x86_64                18-3.el8                                          @BaseOS

Let me know if you require more information or if you would like me to try anything, I am more than happy to help resolve this issue. Thanks!

**Comment by towe75** [comment]
Hi @brickstool ,

thanks for testing the driver.
I will check what's going on.

**Comment by towe75** [comment]
Quick question: did you download the prebuilt binary for your test or did you compile the driver from source?

**Comment by brickstool** [comment]
@towe75 I downloaded the latest prebuilt binary, v0.0.3

**Comment by towe75** [comment]
Like stated in #17: podman 1.4.2 is rather "old", can you try to update it?

**Comment by fuero** [comment]
@brickstool Here are the RPMs I created, hope they help: https://www44.zippyshare.com/v/EvdbAR6X/file.html

**Comment by brickstool** [comment]
@fuero thanks! 

@towe75 I'll give the rpm provided by @fuero a go in a bit and report back.

**Comment by brickstool** [comment]
@towe75 I have tested with podman version 1.7.1 (built from source) and the job successfully runs! Thanks.
