### ISSUE TITLE
Please implement "--hostname"

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#5]
It should be possible to set container's host name from the config, like native Docker driver can do:
https://www.nomadproject.io/docs/drivers/docker.html#hostname

**Comment by towe75** [comment]
Sure. My priority for now is, however, to provide some unit tests before implementing more features.

**Comment by towe75** [comment]
@onlyjob hostname is now configurable via task config, it's documented and has a test

**Comment by onlyjob** [comment]
It works, thank you.
