### ISSUE TITLE
Clean-up containers on exit?

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#6]
After execution of job, `podman ps -a` show stopped containers.
I think it is undesirable to leave them behind by default but regardless from the defaults it would be great to have a configurable option to pass `--rm` when container is started.

Thanks.

**Comment by towe75** [comment]
Best will be to implement this similar to the docker drivers [gc option](https://www.nomadproject.io/docs/drivers/docker.html#gc).

**Comment by towe75** [comment]
@onlyjob i implemented this feature along with tests and a readme snippet. Please give it a try.

**Comment by onlyjob** [comment]
Excellent, thanks.
