### ISSUE TITLE
Please implement support for Podman's "--init"

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#8]
Podman have a useful `--init` option that is worth supporting.

Thanks.

**Comment by towe75** [comment]
Ah, IC. It's simliar to [lxc-execute](https://linuxcontainers.org/lxc/manpages/man1/lxc-execute.1.html). It's for sure useful but i'll focus on some basic network features, first.

**Comment by towe75** [comment]
@onlyjob the driver has now a init and a init_path directive, see latest commit. The readme shows, like usual, a small usage example.

**Comment by onlyjob** [comment]
Awesome, thanks.

I'm not sure if `init_path` should be configurable.
It is defined in the Podman's `/etc/containers/libpod.conf` config file and I am slightly concerned that it can be overridden in Nomad's job specification... I'd rather not introduce duplicated config option that overrides system default.

Thoughts?

Also the defaults.... _catatonit_ is not very common. In Debian we have _tini_ and _dumb-init_ but not _catatonit_... The latter appears to be the youngest of all three and it is unclear to me why it exists and how it is different from _tini_. Anyway this is a minor concern and I could easily override the default in the Debian package...

**Comment by towe75** [comment]
> I'm not sure if init_path should be configurable.

Well, podman offers a command line option --init-path, so i guessed it might be a good idea to expose it in the job configuration. 

> Also the defaults.... catatonit is not very common. 

I am not opinionated here. If init_path is not configured for your job, it will simply fallback to libpod.conf or the podman hardcoded default. 

When i tried --init for the first time on a fedora test vm, it complained that catatonit is not installed. So it's the definitive default in their binary packages. Also i checked their unit test and found catatonit again, so i do the same in my unit test.

I can add a few lines into the readme, if it helps. But i want to keep both init and init_path to give the user full control. 

The driver config would be another place where the default could be maintained, i could add this if it makes sense to you. Then the full search order would have one more level:
job init_path, fallback to driver init_path, fallback to libpod.conf, fallback to podman.exe

**Comment by onlyjob** [comment]
> If init_path is not configured for your job, it will simply fallback to libpod.conf or the podman hardcoded default.

Unfortunately currently it does not work as expected. With merely `init = true` in the job specification there is a following failure:

```
rpc error: code = Unknown desc = failt to start task, could not create container: io.podman.ErrorOccurred(Reason: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory)
```

That's despite `init_path = "/usr/bin/tini-static"` configured in the `/etc/containers/libpod.conf`.

Clearly driver unnecessarily and incorrectly overrides system default with its own.

The obvious problem here is that job specification could not know which init binary is available on the host. By default driver must not impose its preference of the _init_ binary on to Podman (which have its own default).

**Comment by towe75** [comment]
I understand your point and i'll try to reproduce the issue. 

My code has, however, no hardcoded init_path value and so i assumed it will use the libpod.conf setting. Upon creating a container, the driver sets init_path to the literal job spec value (which is a empty string if not specified) and maybe this triggers some podman internal fallback to the compiled-in value. I'll try to omit setting it to empty if it's missing in the job spec, maybe it helps. It smells a bit like a varlink specific podman bug, though.

**Comment by onlyjob** [comment]
On second look it appears that Podman did not respect `libpod.conf/init_path` _when ran under driver-podman_. I could not reproduce the problem with Podman executed directly from command line.

With command line `podman run --init --rm docker.io/library/debian:stable /bin/sh -c "sleep 44"` Podman fails only when `init_path` is not defined in the `libpod.conf`:

```
Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory
```

So clearly Podman's built-in default is to use `catatonit` but for whatever reason under Nomad `libpod.conf/init_path` is ignored...

> My code has, however, no hardcoded init_path value

Yes, I see that but nevertheless somehow it forces Podman to use built-in default for `init_path`...

**Comment by towe75** [comment]
I spent some time and it podman seems to ignore the conf-file init path when using the varlink interface. It does not matter if i populate init-path with an empty string or keep it nil.
For now, i'll work around it by adding a global init-path to the driver configuration. You can open a podman issue, if you want.

**Comment by towe75** [comment]
@onlyjob i checked again and possible both of us made the same mistake: libpod.conf DOES work. 

But you have to make sure to restart your io.podman unit after changing it. It's only interpreted when the unit spawns a new varlink listener. 

Can you please verify?

**Comment by onlyjob** [comment]
Sensational caveat. Indeed restarting `io.podman` picked up changes from `/etc/containers/libpod.conf`. Not sure where it should be documented...

All good, thank you.
