### ISSUE TITLE
Networking: how to map ports?

### ISSUE THREAD

**Issue by onlyjob** [pascomnet/nomad-driver-podman#9]
Apparently [port_map](https://www.nomadproject.io/docs/drivers/docker.html#using-the-port-map) is not yet implemented:

```
Invalid label: No argument or block type is named "port_map".
```

**Comment by towe75** [comment]
Yes. In fact i am currently working on this feature. I'll push it once the unittest is done.
After that i will do a first binary release to attract more people.

**Comment by towe75** [comment]
@onlyjob, it's now possible to use ports and port_map. Syntax is similar to docker driver task config.

**Comment by onlyjob** [comment]
Excellent, thanks. It appears to work properly. :)
